### PR TITLE
Bugfix/79 fix missed source during upgrade

### LINKED ISSUE #79: Fix container restart during upgrade 4.1.0-3 to 4.2.3-1
The reason is a missed source towards `util.sh` in which variables are exported that the upgrade script tries to use.

### LINKED ISSUE #82: Dogu upgrade fails for older Redmine versions without `sort -v` support
With the implementation of #68 a SemVer comparison routine entered the Redmine upgrade scripts. These routines fail in older Redmine versions (f. i. `4.0.5-1`) because the used Bash syntax `sort -v` was not yet introduced (most probably in [Alpine v3.11 in 2019](https://unix.stackexchange.com/a/585795/440116))

Please rewrite the SemVer comparison with means of basic bash functionality.

### PR DESCRIPTION
**Pull request by ppxl**
This PR resolves #79 and fixes missing SQL credentials.

Furthermore, this PR replaces an overly complex version check regex with a easier-to-understand method within the post-upgrade script. A proper upgrade from Redmine v3.x to v4.x could not be checked though because v3.x does not even install properly in my development machine :frowning: 

This PR also resolves #82 and replaces a modern bash semver comparison with one that is more compatible with older Redmine dogu versions.

### CODE REVIEW

File: resources/post-upgrade.sh [hunk 1]
```diff
@@ -25,14 +25,16 @@ function run_postupgrade() {
...
+
   echo "Executing Redmine post-upgrade from ${FROM_VERSION} to ${TO_VERSION}"
 
   if [ "${FROM_VERSION}" = "${TO_VERSION}" ]; then
     echo "FROM and TO versions are the same; Exiting..."
     exit 0
   fi
 
-  if [[ "${FROM_VERSION}" =~ ^v3.*$ || "${FROM_VERSION}" =~ ^[v]*4.((0.5-1)|(1.0-[123]))$ ]]; then
+  if versionXLessOrEqualThanY "${FROM_VERSION}" "4.1.0-3"; then
```
Comment (sklein94) [inline resources/post-upgrade.sh:37]: This looks so nice! I can see in less than a second which versions are mentioned! Much better than a regex.

File: resources/pre-upgrade.sh [hunk 2]
```diff
@@ -40,9 +41,61 @@ function movePluginsToTempDir() {
 }
 
 # versionXLessOrEqualThanY returns true if X is less than or equal to Y; otherwise false
-# This code origins from https://stackoverflow.com/a/4024263/12529534
 function versionXLessOrEqualThanY() {
```
Comment (sklein94) [inline resources/pre-upgrade.sh:44]: Nice Refactoring!

File: resources/pre-upgrade.sh [hunk 3]
```diff
@@ -6,6 +6,7 @@ set -o pipefail
 # WORKDIR is a Dockerfile global variable
 REDMINE_WORK_DIR="${WORKDIR}"
 MIGRATION_TMP_DIR="/var/tmp/redmine/plugins/migration4.4.2.1"
+ERROR_SLEEP_IN_S=300
```
Comment (sklein94) [inline resources/pre-upgrade.sh:9]: I think the idea of this is to prevent the dogu from restarting overy few seconds.
But this should not be an actual usecase as this function is not executed in startup, only when you execute an upgrade.
So in case of failure the upgrade command would sleep for 300 seconds. I dont think this is necessary.

File: resources/post-upgrade.sh (hunk 1 above)
Comment (ppxl) [reply resources/post-upgrade.sh:37]: The problem is that the `util.sh` would be the one from the source redmine, not of the newer target Redmine. Thus the functionality would not exist in older Redmines.

This is also the reason why I rewrote the SemVer functionality.

File: resources/pre-upgrade.sh (hunk 2 above)
Comment (ppxl) [reply resources/pre-upgrade.sh:44]: Oh, this comment is no longer valid :grimacing: The URL references the original solution with `sort -v`.
I am going to delete the comment.

File: resources/pre-upgrade.sh (hunk 3 above)
Comment (ppxl) [reply resources/pre-upgrade.sh:9]: You might have a good point there. Hmmm. Then a simple `exit 1` without sleep will do. Good catch!

Comment (ppxl) [reply resources/pre-upgrade.sh]: - [x] done

File: resources/pre-upgrade.sh (hunk 2 above)
Comment (ppxl) [reply resources/pre-upgrade.sh:43]: - [x] done

**Review by sklein94 — APPROVED** [review]
Code looks good to me!
